import { create } from "zustand";
import { persist } from "zustand/middleware";

type Language = "en" | "es";

interface LanguageStore {
  language: Language;
  setLanguage: (language: Language) => void;
}

export const useLanguage = create<LanguageStore>()(
  persist(
    (set) => ({
      language: "en",
      setLanguage: (language) => set({ language }),
    }),
    {
      name: "marine-store-language",
    }
  )
);

// Translation helper
export const translations = {
  en: {
    // Legal pages
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    imprint: "Imprint",
    warranty: "Warranty",
    
    // Navigation
    home: "Home",
    products: "Products",
    allProducts: "All Products",
    about: "About Us",
    contact: "Contact",
    stores: "Store Locator",
    admin: "Admin",
    
    // Header
    marineExcellence: "Marine Excellence",
    menu: "Menu",
    signIn: "Sign In",
    signOut: "Sign Out",
    signInPrompt: "Sign in to unlock all features",
    myAccount: "My Account",
    myOrders: "My Orders",
    myProfile: "My Profile",
    myWishlist: "My Wishlist",
    
    // Footer
    quickLinks: "Quick Links",
    customerService: "Customer Service",
    legal: "Legal",
    stayConnected: "Stay Connected",
    allRightsReserved: "All rights reserved",
    shippingInfo: "Shipping Info",
    returnPolicy: "Return Policy",
    faq: "FAQ",
    newsletterSubscribe: "Subscribe to our newsletter for exclusive offers and updates",
    
    // Language selector
    language: "Language",
    english: "English",
    spanish: "Spanish",
    
    // Homepage
    premiumMarineLifestyle: "PREMIUM MARINE LIFESTYLE",
    heroTitle: "Where Luxury",
    heroTitleHighlight: "Meets the Sea",
    heroDescription: "Experience the ultimate in floating luxury with our handcrafted marine platforms and accessories",
    exploreCollection: "Explore Collection",
    shopCollection: "Shop Collection",
    viewAllProducts: "View All Products",
    
    // Features
    expertConsultation: "Expert Consultation",
    expertConsultationDesc: "Personalized guidance from marine specialists",
    lifetimeWarranty: "Lifetime Warranty",
    lifetimeWarrantyDesc: "Protected investment in quality",
    ecoFriendly: "Eco-Friendly",
    ecoFriendlyDesc: "Sustainable materials & practices",
    fastDelivery: "Fast Delivery",
    fastDeliveryDesc: "Global shipping within 7-14 days",
    
    // Categories
    shopByCategory: "Shop by Category",
    discoverCurated: "Discover our curated collections",
    explore: "Explore",
    
    // Featured Products
    featuredCollection: "Featured Collection",
    featuredDescription: "Handpicked luxury pieces for the discerning water enthusiast",
    noFeaturedProducts: "No featured products available yet.",
    
    // CTA
    exclusiveCollection: "EXCLUSIVE COLLECTION",
    ctaTitle: "Begin Your",
    ctaTitleHighlight: "Journey",
    ctaDescription: "Transform your aquatic experience with our exclusive collection of premium floating platforms",
    secureCheckout: "Secure Checkout",
    premiumQuality: "Premium Quality",
    freeShipping: "Free Shipping",
    
    // Product Card
    addToCart: "Add to Cart",
    addToWishlist: "Add to Wishlist",
    removeFromWishlist: "Remove from Wishlist",
    outOfStock: "Out of Stock",
    inStock: "In Stock",
    
    // Cart
    shoppingCart: "Shopping Cart",
    yourCart: "Your Cart",
    cartEmpty: "Your cart is empty",
    cartEmptyDesc: "Add products to your cart to get started",
    startShopping: "Start Shopping",
    remove: "Remove",
    subtotal: "Subtotal",
    total: "Total",
    proceedToCheckout: "Proceed to Checkout",
    continueShopping: "Continue Shopping",
    
    // Checkout
    checkout: "Checkout",
    shippingDetails: "Shipping Details",
    paymentDetails: "Payment Details",
    orderSummary: "Order Summary",
    placeOrder: "Place Order",
    processing: "Processing...",
    
    // Orders
    orders: "Orders",
    orderDetails: "Order Details",
    orderNumber: "Order Number",
    orderDate: "Order Date",
    orderStatus: "Order Status",
    orderTotal: "Order Total",
    trackOrder: "Track Order",
    viewOrder: "View Order",
    noOrders: "No orders yet",
    noOrdersDesc: "Start shopping to place your first order",
    
    // Wishlist
    wishlist: "Wishlist",
    myWishlistTitle: "My Wishlist",
    wishlistEmpty: "Your wishlist is empty",
    wishlistEmptyDesc: "Add products to your wishlist to save them for later",
    moveToCart: "Move to Cart",
    
    // Profile
    profile: "Profile",
    personalInfo: "Personal Information",
    name: "Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    
    // Search & Filters
    search: "Search",
    searchProducts: "Search products...",
    filters: "Filters",
    category: "Category",
    priceRange: "Price Range",
    availability: "Availability",
    rating: "Rating",
    sortBy: "Sort By",
    applyFilters: "Apply Filters",
    clearFilters: "Clear Filters",
    noResults: "No results found",
    noResultsDesc: "Try adjusting your search or filters",
    
    // Reviews
    reviews: "Reviews",
    writeReview: "Write a Review",
    reviewRating: "Rating",
    comment: "Comment",
    submit: "Submit",
    
    // Testimonials
    testimonialsTitle: "What Our Customers Say",
    testimonialsDesc: "Real experiences from our satisfied clients",
    
    // Common
    loading: "Loading...",
    error: "Error",
    success: "Success",
    confirm: "Confirm",
    close: "Close",
    yes: "Yes",
    no: "No",
    back: "Back",
    next: "Next",
    previous: "Previous",
    showMore: "Show More",
    showLess: "Show Less",
    readMore: "Read More",
    learnMore: "Learn More",
    
    // Form fields
    firstName: "First Name",
    lastName: "Last Name",
    phoneNumber: "Phone Number",
    city: "City",
    state: "State",
    zipCode: "ZIP Code",
    country: "Country",
    message: "Message",
    subject: "Subject",
    
    // Errors
    required: "This field is required",
    invalidEmail: "Invalid email address",
    invalidPhone: "Invalid phone number",
    errorOccurred: "An error occurred",
    tryAgain: "Please try again",
    
    // Newsletter
    subscribeNewsletter: "Subscribe to Newsletter",
    enterEmail: "Enter your email",
    subscribe: "Subscribe",
    subscribeSuccess: "Successfully subscribed!",
    subscribeError: "Subscription failed",
    
    // Live Chat
    liveChat: "Live Chat",
    startChat: "Start Chat",
    typeMessage: "Type your message...",
    send: "Send",
    
    // About page
    aboutYachtBeach: "About Us",
    navigationExcellence: "Navigating excellence in marine lifestyle. Premium equipment for those who live and breathe the ocean.",
    ourJourney: "Our Journey",
    chartingNewWaters: "Charting New Waters",
    aboutStory1: "Born from a passion for the sea, we emerged as a beacon of quality in marine equipment. We're not just suppliers – we're sailors, divers, and ocean enthusiasts who understand what it means to trust your gear.",
    aboutStory2: "Every product in our collection has been tested in real conditions, from calm harbors to challenging open waters. We believe in equipment that performs when it matters most.",
    ourCoreValues: "Our Core Values",
    coreValuesPrinciples: "The principles that guide every decision we make",
    premiumQualityTitle: "Premium Quality",
    premiumQualityDesc: "Only the finest marine-grade products that withstand the test of time and elements.",
    safetyFirst: "Safety First",
    safetyFirstDesc: "Rigorous testing and certification ensure your adventures are always secure.",
    customerPassion: "Customer Passion",
    customerPassionDesc: "Your satisfaction fuels our commitment to exceptional service and support.",
    expertKnowledge: "Expert Knowledge",
    expertKnowledgeDesc: "Decades of maritime expertise guide our curation and recommendations.",
    ourMission: "Our Mission",
    missionStatement: "To empower maritime enthusiasts with premium equipment that transforms every voyage into an extraordinary experience. We're committed to quality, safety, and innovation – ensuring that whether you're navigating open waters or relaxing on shore, you're equipped for excellence.",
    
    // Contact page
    getInTouch: "Get In Touch",
    haveQuestions: "Have questions? We're here to help you navigate your maritime needs.",
    emailTitle: "Email",
    phoneTitle: "Phone",
    addressTitle: "Address",
    businessHours: "Business Hours",
    businessHoursValue: "Mon-Fri: 9AM-6PM\nSat: 10AM-4PM\nSun: Closed",
    sendUsMessage: "Send Us a Message",
    weRespond24h: "We typically respond within 24 hours",
    yourName: "Your Name",
    emailAddress: "Email Address",
    howCanWeHelp: "How can we help you?",
    tellUsMore: "Tell us more about your inquiry...",
    sendMessage: "Send Message",
    sending: "Sending...",
    
    // FAQ page
    frequentlyAsked: "Frequently Asked Questions",
    quickAnswers: "Quick answers to common questions about our products and services.",
    ordersShipping: "Orders & Shipping",
    howLongShipping: "How long does shipping take?",
    shippingAnswer: "Standard shipping takes 5-7 business days, while express shipping takes 2-3 business days. Orders are typically processed within 1-2 business days. International shipping times vary by destination.",
    freeShippingQ: "Do you offer free shipping?",
    freeShippingAnswer: "Yes! We offer free standard shipping on all orders over €500. The discount is automatically applied at checkout, no code needed.",
    canTrackOrder: "Can I track my order?",
    trackOrderAnswer: "Absolutely! Once your order ships, you'll receive an email with a tracking number. You can also track your order by logging into your account and visiting the \"My Orders\" page.",
    shipInternationally: "Do you ship internationally?",
    internationalAnswer: "Yes, we ship to most countries worldwide. International shipping times and costs vary by destination. Please note that international orders may be subject to customs duties and import taxes.",
    changeCancel: "Can I change or cancel my order?",
    changeCancelAnswer: "If you need to change or cancel your order, please contact us immediately. Once an order has been processed and shipped, we cannot make changes. However, you can return the items according to our return policy.",
    returnsRefunds: "Returns & Refunds",
    whatReturnPolicy: "What is your return policy?",
    returnPolicyAnswer: "We offer a 30-day money-back guarantee. If you're not satisfied with your purchase, you can return it within 30 days of delivery for a full refund. Items must be in original, unused condition with all original packaging.",
    howReturn: "How do I return an item?",
    howReturnAnswer: "Contact our support team with your order number and reason for return. We'll provide you with return instructions and a return authorization. Once we receive and inspect your return, we'll process your refund within 5-7 business days.",
    howLongRefund: "How long does it take to receive a refund?",
    refundTimeAnswer: "Refunds are processed within 5-7 business days after we receive your return. Depending on your bank or credit card company, it may take an additional 3-5 business days for the refund to appear in your account.",
    whoPaysReturn: "Who pays for return shipping?",
    returnShippingAnswer: "Return shipping costs are typically the customer's responsibility, unless the return is due to our error or a defective product. In those cases, we'll provide a prepaid return label.",
    productsSection: "Products",
    productsAuthentic: "Are your products authentic?",
    authenticAnswer: "Absolutely! All our products are 100% authentic and sourced directly from trusted manufacturers and authorized distributors. We guarantee the quality and authenticity of every item we sell.",
    productsWarranty: "Do products come with a warranty?",
    warrantyAnswer: "Many of our products come with manufacturer warranties. Warranty details vary by product and brand. Check the product description for specific warranty information, or contact us for details.",
    whenRestock: "When will out-of-stock items be available?",
    restockAnswer: "Restock dates vary by product. If an item you want is out of stock, please contact us and we'll be happy to provide an estimated restock date or suggest similar alternatives.",
    paymentSecurity: "Payment & Security",
    paymentMethods: "What payment methods do you accept?",
    paymentMethodsAnswer: "We accept all major credit cards (Visa, Mastercard, American Express), as well as various digital payment methods through our secure Stripe payment gateway.",
    isPaymentSecure: "Is my payment information secure?",
    paymentSecureAnswer: "Yes! We use Stripe for payment processing, which employs bank-level security and encryption. We never store your credit card information on our servers. All transactions are protected by SSL encryption.",
    purchaseWithoutAccount: "Can I purchase without creating an account?",
    guestCheckoutAnswer: "Yes! We offer guest checkout, so you can complete your purchase without creating an account. However, creating an account allows you to track orders, save addresses, and enjoy a faster checkout experience.",
    stillHaveQuestions: "Still have questions?",
    cantFindAnswer: "Can't find the answer you're looking for? Our customer support team is here to help.",
    contactGetBack: "Contact us and we'll get back to you as soon as possible",
    
    // Profile page
    manageAccount: "Manage your account information and orders",
    signInToView: "You must sign in to view your profile",
    editProfileInfo: "Edit Profile Information",
    fullName: "Full Name",
    emailCannotChange: "Email address cannot be changed",
    totalOrders: "Total Orders",
    deliveredOrders: "Delivered",
    totalSpent: "Total Spent",
    defaultAddress: "Default Address",
    addAddress: "Add",
    editAddress: "Edit Address",
    noAddressYet: "No address added yet",
    deleteAddress: "Delete Address",
    confirmDeleteAddress: "Are you sure you want to delete your address?",
    addressDeleted: "Address deleted",
    couldNotDelete: "Could not delete address",
    recentOrders: "Recent Orders",
    lastOrders: "Your last 5 orders",
    noOrdersYet: "No orders yet",
    viewAll: "View All",
    memberSince: "Member since:",
    role: "Role",
    userRole: "User",
    adminRole: "Admin",
    streetAddress: "Street Address",
    stateRegion: "State/Region",
    
    // Checkout page
    backToCart: "Back to Cart",
    checkoutAsGuest: "Checking out as a guest",
    contactInformation: "Contact Information",
    sendConfirmation: "We'll send your order confirmation here",
    shippingAddress: "Shipping Address",
    fullNameRequired: "Full name is required",
    streetAddressRequired: "Street address is required",
    cityRequired: "City is required",
    stateRequired: "State is required",
    zipRequired: "ZIP code is required",
    phoneRequired: "Phone is required",
    selectCountry: "Select a country",
    shippingMethod: "Shipping Method",
    selectShipping: "Please select a shipping method",
    estimatedDelivery: "Estimated delivery",
    orderNotes: "Order Notes (Optional)",
    couponCode: "Coupon Code",
    enterCode: "Enter code",
    apply: "Apply",
    applyCoupon: "Apply coupon",
    shipping: "Shipping",
    discount: "Discount",
    completeOrder: "Complete Order",
    securedByStripe: "Secured by Stripe",
    cartIsEmpty: "Your cart is empty",
    cartEmptyAddItems: "Add items to your cart before checkout.",
    
    // Order status
    pending: "Pending",
    orderProcessing: "Processing",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    
    // Orders pages
    viewTrackOrders: "View and track all your orders",
    signInToViewOrders: "Please sign in to view your orders",
    noOrdersYetDesc: "Start shopping to place your first order",
    exploreProducts: "Explore Products",
    delivery: "Delivery",
    orderTracking: "Order Tracking",
    trackYourOrder: "Enter your order number and email to track your shipment",
    enterTrackingInfo: "Enter Tracking Information",
    trackAnother: "Track Another",
    orderPending: "Order Pending",
    orderReceived: "Order Received",
    preparing: "Preparing",
    shipped_status: "Shipped",
    delivered_status: "Delivered",
    cancelled_status: "Cancelled",
    orderItems: "Order Items",
    quantity: "Quantity",
    each: "each",
    shippingDeliveryInfo: "Shipping & Delivery",
    trackingNumber: "Tracking Number",
    payment: "Payment",
    paidByCard: "Paid by credit card",
    awaitingPayment: "Awaiting payment",
    notes: "Notes",
    returnToOrders: "Back to My Orders",
    viewOrderDetails: "You must sign in to view order details",
    
    // Returns page
    returnPolicyTitle: "Return Policy",
    satisfactionPriority: "Your satisfaction is our priority. Easy returns within 30 days.",
    moneyBackGuarantee: "30-Day Money-Back Guarantee",
    standBehindQuality: "We stand behind the quality of our products. If you're not completely satisfied with your purchase, you can return it within 30 days of delivery for a full refund.",
    howToReturn: "How to Return an Item",
    contactUsStep: "Contact Us",
    contactUsDesc: "Email our support team with your order number and reason for return. We'll provide you with a return authorization and instructions.",
    packageItem: "Package Your Item",
    packageDesc: "Securely pack the item in its original packaging (if possible) with all accessories, manuals, and documentation included.",
    shipBack: "Ship It Back",
    shipBackDesc: "Use the prepaid return label we provide (for eligible returns) or ship at your own cost. We recommend using a tracked shipping method.",
    receiveRefund: "Receive Your Refund",
    refundDesc: "Once we receive and inspect your return, we'll process your refund within 5-7 business days to your original payment method.",
    returnEligibility: "Return Eligibility",
    eligibleForReturn: "Eligible for Return",
    originalCondition: "Items in original, unused condition",
    withPackaging: "Items with original packaging and tags",
    within30Days: "Items returned within 30 days",
    defectiveItems: "Defective or damaged items",
    notEligible: "Not Eligible for Return",
    usedItems: "Items that have been used or worn",
    noPackaging: "Items without original packaging",
    customItems: "Custom or personalized items",
    clearanceItems: "Clearance or final sale items",
    refundInformation: "Refund Information",
    processingTime: "Processing Time",
    processingTimeDesc: "Refunds are processed within 5-7 business days after we receive your return. Please note that it may take an additional 3-5 business days for the refund to appear in your account, depending on your bank or credit card company.",
    refundMethod: "Refund Method",
    refundMethodDesc: "All refunds are issued to the original payment method used for the purchase. If you paid with a credit card, the refund will be credited to that card. If you paid via another method, we'll process the refund accordingly.",
    shippingCosts: "Shipping Costs",
    shippingCostsDesc: "Original shipping costs are non-refundable unless the return is due to our error or a defective product. Return shipping costs are the customer's responsibility unless otherwise specified.",
    exchanges: "Exchanges",
    exchangesDesc: "We currently don't offer direct exchanges. If you need a different size, color, or product, please return your original item for a refund and place a new order for the item you want.",
    exchangesProcess: "This process ensures you receive your preferred item as quickly as possible.",
    damagedDefective: "Received a Damaged or Defective Item?",
    damagedDesc: "We're sorry if your item arrived damaged or defective. Please contact us immediately with photos of the damage and your order number. We'll arrange for a replacement or full refund, including return shipping costs.",
    inspectOrder: "Please inspect your order upon receipt and report any issues within 48 hours.",
    
    // Shipping page
    shippingTitle: "Shipping Information",
    fastReliableDelivery: "Fast, reliable delivery to get your products to you quickly and safely.",
    shippingMethods: "Shipping Methods",
    standardShipping: "Standard Shipping",
    standardDays: "5-7 business days",
    economicalOption: "Our most economical option, perfect for non-urgent orders.",
    expressShipping: "Express Shipping",
    expressDays: "2-3 business days",
    fasterDelivery: "Faster delivery for when you need your items quickly.",
    freeShippingOver: "Enjoy free standard shipping on all orders over €500. No code needed – the discount is automatically applied at checkout.",
    orderProcessingTitle: "Order Processing",
    orderProcessingDesc: "Orders are typically processed within 1-2 business days. You'll receive a confirmation email with tracking information once your order ships.",
    importantNote: "Important Note:",
    weekendOrders: "Orders placed on weekends or holidays will be processed on the next business day. During peak seasons, processing times may be slightly longer.",
    internationalShipping: "International Shipping",
    worldwideDelivery: "Worldwide Delivery",
    internationalTimes: "We ship to most countries worldwide. International shipping times vary by destination:",
    europe: "Europe",
    europeDays: "5-10 business days",
    northAmerica: "North America",
    northAmericaDays: "7-14 business days",
    asiaPacific: "Asia & Pacific",
    asiaDays: "10-20 business days",
    restWorld: "Rest of World",
    restWorldDays: "15-30 business days",
    customsDuties: "Customs & Duties:",
    customsDutiesDesc: "International orders may be subject to import duties and taxes, which are the responsibility of the customer. These charges are not included in our prices.",
    orderTrackingTitle: "Order Tracking",
    trackingDesc1: "Once your order ships, you'll receive an email with a tracking number. You can use this number to track your package's journey to your doorstep.",
    trackingDesc2: "You can also track your order by logging into your account and visiting the \"My Orders\" page, where you'll find real-time updates on all your orders.",
    questionsShipping: "Questions about shipping?",
    questionsShippingDesc: "If you have any questions about our shipping policies or need assistance with an order, please don't hesitate to contact us.",
    contactSupport: "Contact our support team for help with shipping questions",
    
    // Stores page
    findOurStores: "Find Our Stores",
    visitShowrooms: "Visit our premium showrooms in the world's most exclusive marinas and beach destinations. Experience luxury yacht equipment and beach accessories in person.",
    allStoreLocations: "All Store Locations",
    showingDetails: "Showing details for",
    clickMarkerOrSelect: "Click on a map marker or select a store below",
    clickForDetails: "Click for details",
    cantVisit: "Can't Visit Us in Person?",
    shopOnlineDesc: "Shop our entire collection online and enjoy worldwide shipping. Our customer service team is available 24/7 to assist you.",
    shopOnline: "Shop Online",
    contactUs: "Contact Us",
    
    // Stores regions
    mediterranean: "Mediterranean",
    americas: "Americas",
    caribbean: "Caribbean",
    middleEast: "Middle East",
    
    // NotFound page
    pageNotFound: "Page Not Found",
    pageNotExist: "This page does not exist.",
    returnHome: "Return to Home",
    
    // Checkout success/cancel
    paymentSuccessful: "Payment Successful!",
    orderCreated: "Your order has been successfully created. Order details have been sent to your email address.",
    viewMyOrders: "View My Orders",
    thankYou: "Thank you! 🎉",
    paymentCancelled: "Payment Cancelled",
    paymentCancelledDesc: "Your payment has been cancelled. Your cart items have been preserved.",
    returnToCart: "Return to Cart",
  },
  es: {
    // Legal pages
    privacy: "Política de Privacidad",
    terms: "Términos de Servicio",
    imprint: "Aviso Legal",
    warranty: "Garantía",
    
    // Navigation
    home: "Inicio",
    products: "Productos",
    allProducts: "Todos los Productos",
    about: "Sobre Nosotros",
    contact: "Contacto",
    stores: "Localizador de Tiendas",
    admin: "Administración",
    
    // Header
    marineExcellence: "Excelencia Marina",
    menu: "Menú",
    signIn: "Iniciar Sesión",
    signOut: "Cerrar Sesión",
    signInPrompt: "Inicia sesión para desbloquear todas las funciones",
    myAccount: "Mi Cuenta",
    myOrders: "Mis Pedidos",
    myProfile: "Mi Perfil",
    myWishlist: "Mi Lista de Deseos",
    
    // Footer
    quickLinks: "Enlaces Rápidos",
    customerService: "Servicio al Cliente",
    legal: "Legal",
    stayConnected: "Mantente Conectado",
    allRightsReserved: "Todos los derechos reservados",
    shippingInfo: "Información de Envío",
    returnPolicy: "Política de Devolución",
    faq: "Preguntas Frecuentes",
    newsletterSubscribe: "Suscríbete a nuestro boletín para ofertas exclusivas y actualizaciones",
    
    // Language selector
    language: "Idioma",
    english: "Inglés",
    spanish: "Español",
    
    // Homepage
    premiumMarineLifestyle: "ESTILO DE VIDA MARINO PREMIUM",
    heroTitle: "Donde el Lujo",
    heroTitleHighlight: "Se Encuentra con el Mar",
    heroDescription: "Experimenta lo último en lujo flotante con nuestras plataformas marinas artesanales y accesorios",
    exploreCollection: "Explorar Colección",
    shopCollection: "Comprar Colección",
    viewAllProducts: "Ver Todos los Productos",
    
    // Features
    expertConsultation: "Consultoría Experta",
    expertConsultationDesc: "Orientación personalizada de especialistas marinos",
    lifetimeWarranty: "Garantía de por Vida",
    lifetimeWarrantyDesc: "Inversión protegida en calidad",
    ecoFriendly: "Ecológico",
    ecoFriendlyDesc: "Materiales y prácticas sostenibles",
    fastDelivery: "Entrega Rápida",
    fastDeliveryDesc: "Envío global en 7-14 días",
    
    // Categories
    shopByCategory: "Comprar por Categoría",
    discoverCurated: "Descubre nuestras colecciones seleccionadas",
    explore: "Explorar",
    
    // Featured Products
    featuredCollection: "Colección Destacada",
    featuredDescription: "Piezas de lujo seleccionadas para el entusiasta del agua exigente",
    noFeaturedProducts: "Aún no hay productos destacados disponibles.",
    
    // CTA
    exclusiveCollection: "COLECCIÓN EXCLUSIVA",
    ctaTitle: "Comienza Tu",
    ctaTitleHighlight: "Viaje",
    ctaDescription: "Transforma tu experiencia acuática con nuestra colección exclusiva de plataformas flotantes premium",
    secureCheckout: "Pago Seguro",
    premiumQuality: "Calidad Premium",
    freeShipping: "Envío Gratis",
    
    // Product Card
    addToCart: "Añadir al Carrito",
    addToWishlist: "Añadir a Lista de Deseos",
    removeFromWishlist: "Quitar de Lista de Deseos",
    outOfStock: "Agotado",
    inStock: "En Stock",
    
    // Cart
    shoppingCart: "Carrito de Compras",
    yourCart: "Tu Carrito",
    cartEmpty: "Tu carrito está vacío",
    cartEmptyDesc: "Añade productos a tu carrito para comenzar",
    startShopping: "Comenzar a Comprar",
    remove: "Eliminar",
    subtotal: "Subtotal",
    total: "Total",
    proceedToCheckout: "Proceder al Pago",
    continueShopping: "Continuar Comprando",
    
    // Checkout
    checkout: "Pagar",
    shippingDetails: "Detalles de Envío",
    paymentDetails: "Detalles de Pago",
    orderSummary: "Resumen del Pedido",
    placeOrder: "Realizar Pedido",
    processing: "Procesando...",
    
    // Orders
    orders: "Pedidos",
    orderDetails: "Detalles del Pedido",
    orderNumber: "Número de Pedido",
    orderDate: "Fecha del Pedido",
    orderStatus: "Estado del Pedido",
    orderTotal: "Total del Pedido",
    trackOrder: "Rastrear Pedido",
    viewOrder: "Ver Pedido",
    noOrders: "Aún no hay pedidos",
    noOrdersDesc: "Comienza a comprar para realizar tu primer pedido",
    
    // Wishlist
    wishlist: "Lista de Deseos",
    myWishlistTitle: "Mi Lista de Deseos",
    wishlistEmpty: "Tu lista de deseos está vacía",
    wishlistEmptyDesc: "Añade productos a tu lista de deseos para guardarlos para más tarde",
    moveToCart: "Mover al Carrito",
    
    // Profile
    profile: "Perfil",
    personalInfo: "Información Personal",
    name: "Nombre",
    email: "Correo Electrónico",
    phone: "Teléfono",
    address: "Dirección",
    save: "Guardar",
    cancel: "Cancelar",
    edit: "Editar",
    
    // Search & Filters
    search: "Buscar",
    searchProducts: "Buscar productos...",
    filters: "Filtros",
    category: "Categoría",
    priceRange: "Rango de Precio",
    availability: "Disponibilidad",
    rating: "Calificación",
    sortBy: "Ordenar Por",
    applyFilters: "Aplicar Filtros",
    clearFilters: "Limpiar Filtros",
    noResults: "No se encontraron resultados",
    noResultsDesc: "Intenta ajustar tu búsqueda o filtros",
    
    // Reviews
    reviews: "Reseñas",
    writeReview: "Escribir Reseña",
    reviewRating: "Calificación",
    comment: "Comentario",
    submit: "Enviar",
    
    // Testimonials
    testimonialsTitle: "Lo Que Dicen Nuestros Clientes",
    testimonialsDesc: "Experiencias reales de nuestros clientes satisfechos",
    
    // Common
    loading: "Cargando...",
    error: "Error",
    success: "Éxito",
    confirm: "Confirmar",
    close: "Cerrar",
    yes: "Sí",
    no: "No",
    back: "Atrás",
    next: "Siguiente",
    previous: "Anterior",
    showMore: "Mostrar Más",
    showLess: "Mostrar Menos",
    readMore: "Leer Más",
    learnMore: "Aprender Más",
    
    // Form fields
    firstName: "Nombre",
    lastName: "Apellido",
    phoneNumber: "Número de Teléfono",
    city: "Ciudad",
    state: "Estado",
    zipCode: "Código Postal",
    country: "País",
    message: "Mensaje",
    subject: "Asunto",
    
    // Errors
    required: "Este campo es obligatorio",
    invalidEmail: "Dirección de correo electrónico inválida",
    invalidPhone: "Número de teléfono inválido",
    errorOccurred: "Ocurrió un error",
    tryAgain: "Por favor, inténtalo de nuevo",
    
    // Newsletter
    subscribeNewsletter: "Suscribirse al Boletín",
    enterEmail: "Ingresa tu correo electrónico",
    subscribe: "Suscribirse",
    subscribeSuccess: "¡Suscripción exitosa!",
    subscribeError: "Error en la suscripción",
    
    // Live Chat
    liveChat: "Chat en Vivo",
    startChat: "Iniciar Chat",
    typeMessage: "Escribe tu mensaje...",
    send: "Enviar",
    
    // About page
    aboutYachtBeach: "Sobre Nosotros",
    navigationExcellence: "Navegando la excelencia en estilo de vida marino. Equipamiento premium para quienes viven y respiran el océano.",
    ourJourney: "Nuestro Viaje",
    chartingNewWaters: "Trazando Nuevas Aguas",
    aboutStory1: "Nacido de una pasión por el mar, emergimos como un faro de calidad en equipamiento marino. No somos solo proveedores – somos navegantes, buzos y entusiastas del océano que entendemos lo que significa confiar en tu equipo.",
    aboutStory2: "Cada producto en nuestra colección ha sido probado en condiciones reales, desde puertos tranquilos hasta aguas abiertas desafiantes. Creemos en equipamiento que funciona cuando más importa.",
    ourCoreValues: "Nuestros Valores Fundamentales",
    coreValuesPrinciples: "Los principios que guían cada decisión que tomamos",
    premiumQualityTitle: "Calidad Premium",
    premiumQualityDesc: "Solo los mejores productos de grado marino que resisten la prueba del tiempo y los elementos.",
    safetyFirst: "Seguridad Primero",
    safetyFirstDesc: "Pruebas rigurosas y certificación aseguran que tus aventuras sean siempre seguras.",
    customerPassion: "Pasión por el Cliente",
    customerPassionDesc: "Tu satisfacción alimenta nuestro compromiso con un servicio y soporte excepcionales.",
    expertKnowledge: "Conocimiento Experto",
    expertKnowledgeDesc: "Décadas de experiencia marítima guían nuestra selección y recomendaciones.",
    ourMission: "Nuestra Misión",
    missionStatement: "Empoderar a los entusiastas marítimos con equipamiento premium que transforma cada viaje en una experiencia extraordinaria. Estamos comprometidos con la calidad, seguridad e innovación – asegurando que ya sea navegando aguas abiertas o relajándote en la orilla, estés equipado para la excelencia.",
    
    // Contact page
    getInTouch: "Ponte en Contacto",
    haveQuestions: "¿Tienes preguntas? Estamos aquí para ayudarte a navegar tus necesidades marítimas.",
    emailTitle: "Correo Electrónico",
    phoneTitle: "Teléfono",
    addressTitle: "Dirección",
    businessHours: "Horario de Atención",
    businessHoursValue: "Lun-Vie: 9AM-6PM\nSáb: 10AM-4PM\nDom: Cerrado",
    sendUsMessage: "Envíanos un Mensaje",
    weRespond24h: "Típicamente respondemos en 24 horas",
    yourName: "Tu Nombre",
    emailAddress: "Dirección de Correo Electrónico",
    howCanWeHelp: "¿Cómo podemos ayudarte?",
    tellUsMore: "Cuéntanos más sobre tu consulta...",
    sendMessage: "Enviar Mensaje",
    sending: "Enviando...",
    
    // FAQ page
    frequentlyAsked: "Preguntas Frecuentes",
    quickAnswers: "Respuestas rápidas a preguntas comunes sobre nuestros productos y servicios.",
    ordersShipping: "Pedidos y Envíos",
    howLongShipping: "¿Cuánto tarda el envío?",
    shippingAnswer: "El envío estándar tarda 5-7 días hábiles, mientras que el envío express tarda 2-3 días hábiles. Los pedidos generalmente se procesan dentro de 1-2 días hábiles. Los tiempos de envío internacional varían según el destino.",
    freeShippingQ: "¿Ofrecen envío gratis?",
    freeShippingAnswer: "¡Sí! Ofrecemos envío estándar gratis en todos los pedidos superiores a €500. El descuento se aplica automáticamente al finalizar la compra, no se necesita código.",
    canTrackOrder: "¿Puedo rastrear mi pedido?",
    trackOrderAnswer: "¡Absolutamente! Una vez que tu pedido se envíe, recibirás un correo electrónico con un número de seguimiento. También puedes rastrear tu pedido iniciando sesión en tu cuenta y visitando la página \"Mis Pedidos\".",
    shipInternationally: "¿Hacen envíos internacionales?",
    internationalAnswer: "Sí, enviamos a la mayoría de los países del mundo. Los tiempos y costos de envío internacional varían según el destino. Ten en cuenta que los pedidos internacionales pueden estar sujetos a aranceles aduaneros e impuestos de importación.",
    changeCancel: "¿Puedo cambiar o cancelar mi pedido?",
    changeCancelAnswer: "Si necesitas cambiar o cancelar tu pedido, contáctanos inmediatamente. Una vez que un pedido ha sido procesado y enviado, no podemos hacer cambios. Sin embargo, puedes devolver los artículos según nuestra política de devolución.",
    returnsRefunds: "Devoluciones y Reembolsos",
    whatReturnPolicy: "¿Cuál es su política de devolución?",
    returnPolicyAnswer: "Ofrecemos una garantía de devolución de dinero de 30 días. Si no estás satisfecho con tu compra, puedes devolverla dentro de los 30 días posteriores a la entrega para un reembolso completo. Los artículos deben estar en condición original y sin usar con todo el embalaje original.",
    howReturn: "¿Cómo devuelvo un artículo?",
    howReturnAnswer: "Contacta a nuestro equipo de soporte con tu número de pedido y el motivo de la devolución. Te proporcionaremos instrucciones de devolución y una autorización de devolución. Una vez que recibamos e inspeccionemos tu devolución, procesaremos tu reembolso dentro de 5-7 días hábiles.",
    howLongRefund: "¿Cuánto tiempo tarda en recibirse un reembolso?",
    refundTimeAnswer: "Los reembolsos se procesan dentro de 5-7 días hábiles después de que recibamos tu devolución. Dependiendo de tu banco o compañía de tarjeta de crédito, puede tomar 3-5 días hábiles adicionales para que el reembolso aparezca en tu cuenta.",
    whoPaysReturn: "¿Quién paga el envío de devolución?",
    returnShippingAnswer: "Los costos de envío de devolución son típicamente responsabilidad del cliente, a menos que la devolución se deba a nuestro error o un producto defectuoso. En esos casos, proporcionaremos una etiqueta de devolución prepagada.",
    productsSection: "Productos",
    productsAuthentic: "¿Son auténticos sus productos?",
    authenticAnswer: "¡Absolutamente! Todos nuestros productos son 100% auténticos y provienen directamente de fabricantes confiables y distribuidores autorizados. Garantizamos la calidad y autenticidad de cada artículo que vendemos.",
    productsWarranty: "¿Los productos vienen con garantía?",
    warrantyAnswer: "Muchos de nuestros productos vienen con garantías del fabricante. Los detalles de la garantía varían según el producto y la marca. Consulta la descripción del producto para información específica de garantía, o contáctanos para más detalles.",
    whenRestock: "¿Cuándo estarán disponibles los artículos agotados?",
    restockAnswer: "Las fechas de reabastecimiento varían según el producto. Si un artículo que deseas está agotado, contáctanos y estaremos encantados de proporcionarte una fecha estimada de reabastecimiento o sugerir alternativas similares.",
    paymentSecurity: "Pago y Seguridad",
    paymentMethods: "¿Qué métodos de pago aceptan?",
    paymentMethodsAnswer: "Aceptamos todas las principales tarjetas de crédito (Visa, Mastercard, American Express), así como varios métodos de pago digital a través de nuestra pasarela de pago segura Stripe.",
    isPaymentSecure: "¿Es segura mi información de pago?",
    paymentSecureAnswer: "¡Sí! Usamos Stripe para el procesamiento de pagos, que emplea seguridad y encriptación de nivel bancario. Nunca almacenamos tu información de tarjeta de crédito en nuestros servidores. Todas las transacciones están protegidas por encriptación SSL.",
    purchaseWithoutAccount: "¿Puedo comprar sin crear una cuenta?",
    guestCheckoutAnswer: "¡Sí! Ofrecemos pago como invitado, para que puedas completar tu compra sin crear una cuenta. Sin embargo, crear una cuenta te permite rastrear pedidos, guardar direcciones y disfrutar de una experiencia de pago más rápida.",
    stillHaveQuestions: "¿Aún tienes preguntas?",
    cantFindAnswer: "¿No encuentras la respuesta que buscas? Nuestro equipo de soporte al cliente está aquí para ayudar.",
    contactGetBack: "Contáctanos y te responderemos lo antes posible",
    
    // Profile page
    manageAccount: "Administra la información de tu cuenta y pedidos",
    signInToView: "Debes iniciar sesión para ver tu perfil",
    editProfileInfo: "Editar Información del Perfil",
    fullName: "Nombre Completo",
    emailCannotChange: "La dirección de correo electrónico no se puede cambiar",
    totalOrders: "Total de Pedidos",
    deliveredOrders: "Entregados",
    totalSpent: "Total Gastado",
    defaultAddress: "Dirección Predeterminada",
    addAddress: "Agregar",
    editAddress: "Editar Dirección",
    noAddressYet: "Aún no se ha agregado ninguna dirección",
    deleteAddress: "Eliminar Dirección",
    confirmDeleteAddress: "¿Estás seguro de que quieres eliminar tu dirección?",
    addressDeleted: "Dirección eliminada",
    couldNotDelete: "No se pudo eliminar la dirección",
    recentOrders: "Pedidos Recientes",
    lastOrders: "Tus últimos 5 pedidos",
    noOrdersYet: "Aún no hay pedidos",
    viewAll: "Ver Todos",
    memberSince: "Miembro desde:",
    role: "Rol",
    userRole: "Usuario",
    adminRole: "Administrador",
    streetAddress: "Dirección",
    stateRegion: "Estado/Región",
    
    // Checkout page
    backToCart: "Volver al Carrito",
    checkoutAsGuest: "Pagando como invitado",
    contactInformation: "Información de Contacto",
    sendConfirmation: "Enviaremos tu confirmación de pedido aquí",
    shippingAddress: "Dirección de Envío",
    fullNameRequired: "El nombre completo es obligatorio",
    streetAddressRequired: "La dirección es obligatoria",
    cityRequired: "La ciudad es obligatoria",
    stateRequired: "El estado es obligatorio",
    zipRequired: "El código postal es obligatorio",
    phoneRequired: "El teléfono es obligatorio",
    selectCountry: "Selecciona un país",
    shippingMethod: "Método de Envío",
    selectShipping: "Por favor selecciona un método de envío",
    estimatedDelivery: "Entrega estimada",
    orderNotes: "Notas del Pedido (Opcional)",
    couponCode: "Código de Cupón",
    enterCode: "Ingresar código",
    apply: "Aplicar",
    applyCoupon: "Aplicar cupón",
    shipping: "Envío",
    discount: "Descuento",
    completeOrder: "Completar Pedido",
    securedByStripe: "Protegido por Stripe",
    cartIsEmpty: "Tu carrito está vacío",
    cartEmptyAddItems: "Añade artículos a tu carrito antes de pagar.",
    
    // Order status
    pending: "Pendiente",
    orderProcessing: "Procesando",
    shipped: "Enviado",
    delivered: "Entregado",
    cancelled: "Cancelado",
    
    // Orders pages
    viewTrackOrders: "Ver y rastrear todos tus pedidos",
    signInToViewOrders: "Por favor inicia sesión para ver tus pedidos",
    noOrdersYetDesc: "Comienza a comprar para realizar tu primer pedido",
    exploreProducts: "Explorar Productos",
    delivery: "Entrega",
    orderTracking: "Seguimiento del Pedido",
    trackYourOrder: "Ingresa tu número de pedido y correo electrónico para rastrear tu envío",
    enterTrackingInfo: "Ingresar Información de Seguimiento",
    trackAnother: "Rastrear Otro",
    orderPending: "Pedido Pendiente",
    orderReceived: "Pedido Recibido",
    preparing: "Preparando",
    shipped_status: "Enviado",
    delivered_status: "Entregado",
    cancelled_status: "Cancelado",
    orderItems: "Artículos del Pedido",
    quantity: "Cantidad",
    each: "cada uno",
    shippingDeliveryInfo: "Envío y Entrega",
    trackingNumber: "Número de Seguimiento",
    payment: "Pago",
    paidByCard: "Pagado con tarjeta de crédito",
    awaitingPayment: "Esperando pago",
    notes: "Notas",
    returnToOrders: "Volver a Mis Pedidos",
    viewOrderDetails: "Debes iniciar sesión para ver los detalles del pedido",
    
    // Returns page
    returnPolicyTitle: "Política de Devolución",
    satisfactionPriority: "Tu satisfacción es nuestra prioridad. Devoluciones fáciles dentro de 30 días.",
    moneyBackGuarantee: "Garantía de Devolución de Dinero de 30 Días",
    standBehindQuality: "Respaldamos la calidad de nuestros productos. Si no estás completamente satisfecho con tu compra, puedes devolverla dentro de los 30 días posteriores a la entrega para un reembolso completo.",
    howToReturn: "Cómo Devolver un Artículo",
    contactUsStep: "Contáctanos",
    contactUsDesc: "Envía un correo electrónico a nuestro equipo de soporte con tu número de pedido y el motivo de la devolución. Te proporcionaremos una autorización de devolución e instrucciones.",
    packageItem: "Empaca tu Artículo",
    packageDesc: "Empaca de forma segura el artículo en su embalaje original (si es posible) con todos los accesorios, manuales y documentación incluidos.",
    shipBack: "Envíalo de Vuelta",
    shipBackDesc: "Usa la etiqueta de devolución prepagada que proporcionamos (para devoluciones elegibles) o envía a tu propio costo. Recomendamos usar un método de envío con seguimiento.",
    receiveRefund: "Recibe tu Reembolso",
    refundDesc: "Una vez que recibamos e inspeccionemos tu devolución, procesaremos tu reembolso dentro de 5-7 días hábiles a tu método de pago original.",
    returnEligibility: "Elegibilidad de Devolución",
    eligibleForReturn: "Elegible para Devolución",
    originalCondition: "Artículos en condición original y sin usar",
    withPackaging: "Artículos con embalaje y etiquetas originales",
    within30Days: "Artículos devueltos dentro de 30 días",
    defectiveItems: "Artículos defectuosos o dañados",
    notEligible: "No Elegible para Devolución",
    usedItems: "Artículos que han sido usados o llevados puestos",
    noPackaging: "Artículos sin embalaje original",
    customItems: "Artículos personalizados",
    clearanceItems: "Artículos en liquidación o venta final",
    refundInformation: "Información de Reembolso",
    processingTime: "Tiempo de Procesamiento",
    processingTimeDesc: "Los reembolsos se procesan dentro de 5-7 días hábiles después de que recibamos tu devolución. Ten en cuenta que puede tomar 3-5 días hábiles adicionales para que el reembolso aparezca en tu cuenta, dependiendo de tu banco o compañía de tarjeta de crédito.",
    refundMethod: "Método de Reembolso",
    refundMethodDesc: "Todos los reembolsos se emiten al método de pago original utilizado para la compra. Si pagaste con tarjeta de crédito, el reembolso se acreditará a esa tarjeta. Si pagaste a través de otro método, procesaremos el reembolso en consecuencia.",
    shippingCosts: "Costos de Envío",
    shippingCostsDesc: "Los costos de envío originales no son reembolsables a menos que la devolución se deba a nuestro error o un producto defectuoso. Los costos de envío de devolución son responsabilidad del cliente a menos que se especifique lo contrario.",
    exchanges: "Cambios",
    exchangesDesc: "Actualmente no ofrecemos cambios directos. Si necesitas un tamaño, color o producto diferente, devuelve tu artículo original para un reembolso y realiza un nuevo pedido por el artículo que deseas.",
    exchangesProcess: "Este proceso asegura que recibas tu artículo preferido lo más rápido posible.",
    damagedDefective: "¿Recibiste un Artículo Dañado o Defectuoso?",
    damagedDesc: "Lamentamos si tu artículo llegó dañado o defectuoso. Contáctanos inmediatamente con fotos del daño y tu número de pedido. Organizaremos un reemplazo o reembolso completo, incluyendo los costos de envío de devolución.",
    inspectOrder: "Inspecciona tu pedido al recibirlo e informa cualquier problema dentro de las 48 horas.",
    
    // Shipping page
    shippingTitle: "Información de Envío",
    fastReliableDelivery: "Entrega rápida y confiable para que tus productos lleguen de manera rápida y segura.",
    shippingMethods: "Métodos de Envío",
    standardShipping: "Envío Estándar",
    standardDays: "5-7 días hábiles",
    economicalOption: "Nuestra opción más económica, perfecta para pedidos no urgentes.",
    expressShipping: "Envío Express",
    expressDays: "2-3 días hábiles",
    fasterDelivery: "Entrega más rápida cuando necesitas tus artículos rápidamente.",
    freeShippingOver: "Disfruta de envío estándar gratis en todos los pedidos superiores a €500. No se necesita código – el descuento se aplica automáticamente al finalizar la compra.",
    orderProcessingTitle: "Procesamiento de Pedidos",
    orderProcessingDesc: "Los pedidos se procesan típicamente dentro de 1-2 días hábiles. Recibirás un correo electrónico de confirmación con información de seguimiento una vez que tu pedido sea enviado.",
    importantNote: "Nota Importante:",
    weekendOrders: "Los pedidos realizados en fines de semana o días festivos se procesarán el siguiente día hábil. Durante temporadas altas, los tiempos de procesamiento pueden ser ligeramente más largos.",
    internationalShipping: "Envío Internacional",
    worldwideDelivery: "Entrega Mundial",
    internationalTimes: "Enviamos a la mayoría de los países del mundo. Los tiempos de envío internacional varían según el destino:",
    europe: "Europa",
    europeDays: "5-10 días hábiles",
    northAmerica: "América del Norte",
    northAmericaDays: "7-14 días hábiles",
    asiaPacific: "Asia y Pacífico",
    asiaDays: "10-20 días hábiles",
    restWorld: "Resto del Mundo",
    restWorldDays: "15-30 días hábiles",
    customsDuties: "Aranceles Aduaneros:",
    customsDutiesDesc: "Los pedidos internacionales pueden estar sujetos a aranceles de importación e impuestos, que son responsabilidad del cliente. Estos cargos no están incluidos en nuestros precios.",
    orderTrackingTitle: "Seguimiento de Pedidos",
    trackingDesc1: "Una vez que tu pedido sea enviado, recibirás un correo electrónico con un número de seguimiento. Puedes usar este número para rastrear el viaje de tu paquete hasta tu puerta.",
    trackingDesc2: "También puedes rastrear tu pedido iniciando sesión en tu cuenta y visitando la página \"Mis Pedidos\", donde encontrarás actualizaciones en tiempo real de todos tus pedidos.",
    questionsShipping: "¿Preguntas sobre envío?",
    questionsShippingDesc: "Si tienes alguna pregunta sobre nuestras políticas de envío o necesitas asistencia con un pedido, no dudes en contactarnos.",
    contactSupport: "Contacta a nuestro equipo de soporte para ayuda con preguntas de envío",
    
    // Stores page
    findOurStores: "Encuentra Nuestras Tiendas",
    visitShowrooms: "Visita nuestras salas de exhibición premium en los puertos deportivos y destinos de playa más exclusivos del mundo. Experimenta equipamiento de yates de lujo y accesorios de playa en persona.",
    allStoreLocations: "Todas las Ubicaciones de Tiendas",
    showingDetails: "Mostrando detalles para",
    clickMarkerOrSelect: "Haz clic en un marcador del mapa o selecciona una tienda abajo",
    clickForDetails: "Haz clic para detalles",
    cantVisit: "¿No Puedes Visitarnos en Persona?",
    shopOnlineDesc: "Compra toda nuestra colección en línea y disfruta del envío mundial. Nuestro equipo de servicio al cliente está disponible 24/7 para asistirte.",
    shopOnline: "Comprar en Línea",
    contactUs: "Contáctanos",
    
    // Stores regions
    mediterranean: "Mediterráneo",
    americas: "Américas",
    caribbean: "Caribe",
    middleEast: "Medio Oriente",
    
    // NotFound page
    pageNotFound: "Página No Encontrada",
    pageNotExist: "Esta página no existe.",
    returnHome: "Volver al Inicio",
    
    // Checkout success/cancel
    paymentSuccessful: "¡Pago Exitoso!",
    orderCreated: "Tu pedido ha sido creado exitosamente. Los detalles del pedido han sido enviados a tu dirección de correo electrónico.",
    viewMyOrders: "Ver Mis Pedidos",
    thankYou: "¡Gracias! 🎉",
    paymentCancelled: "Pago Cancelado",
    paymentCancelledDesc: "Tu pago ha sido cancelado. Los artículos de tu carrito se han conservado.",
    returnToCart: "Volver al Carrito",
  },
};

export const useTranslation = () => {
  const { language } = useLanguage();
  
  const t = (key: keyof typeof translations.en): string => {
    return translations[language][key] || translations.en[key] || key;
  };
  
  return { t, language };
};

export const getPageSlug = (basePage: string, language: Language): string => {
  const slugs: Record<string, Record<Language, string>> = {
    privacy: { en: "privacy", es: "privacidad" },
    terms: { en: "terms", es: "terminos" },
    imprint: { en: "imprint", es: "aviso-legal" },
    warranty: { en: "warranty", es: "garantia" },
  };
  
  return slugs[basePage]?.[language] || basePage;
};
